// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1zivQsiIrnwkqUTMHDLgxX23-qeNqqIw',
    appId: '1:514330635774:web:37d7faf665ea24a4c864af',
    messagingSenderId: '514330635774',
    projectId: 'codersguidedune',
    authDomain: 'codersguidedune.firebaseapp.com',
    storageBucket: 'codersguidedune.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDvG_wagTrnyVN2k5IziAeCy1AJd66Z8',
    appId: '1:514330635774:android:e5c2ecf3823d2787c864af',
    messagingSenderId: '514330635774',
    projectId: 'codersguidedune',
    storageBucket: 'codersguidedune.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaeBgYaGc5DbJRqPqO9IBzclabHuUPvoE',
    appId: '1:514330635774:ios:f6931097fca22537c864af',
    messagingSenderId: '514330635774',
    projectId: 'codersguidedune',
    storageBucket: 'codersguidedune.appspot.com',
    iosBundleId: 'com.example.codersGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaeBgYaGc5DbJRqPqO9IBzclabHuUPvoE',
    appId: '1:514330635774:ios:fa733184234e709ac864af',
    messagingSenderId: '514330635774',
    projectId: 'codersguidedune',
    storageBucket: 'codersguidedune.appspot.com',
    iosBundleId: 'com.example.codersGuide.RunnerTests',
  );
}
